services:
  brave-search:
    build: ./brave-search
    ports:
      - "8000:8000"
    env_file: ./.env
    environment:
      - BRAVE_API_KEY=${BRAVE_API_KEY}
    restart: unless-stopped

  github:
    build: ./github
    ports:
      - "8002:8002"
    env_file: ./.env
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: unless-stopped

  memory:
    build: ./memory
    ports:
      - "8004:8004"
    volumes:
      - ./memory-data:/app/data
    restart: unless-stopped
